# Generated by Django 5.1.4 on 2025-03-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogmodel_created_at_blogmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcommentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
